markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
highlighter: pygments
safe: true

gems: [jekyll-paginate]
paginate: 8
paginate_path: "page:num"

# presonal config
domain: tguduru.github.io
title: Guduru, Thirupathi Reddy's Blog
description: Learn your way...
author: Guduru, Thirupathi Reddy
email: email
github: tguduru

config:
  js_dir:
  img_dir:
  css_dir:
