#
# Basic settings.
#
#baseurl: http://localhost:4000
baseurl: http://tguduru.github.io
title: Guduru,Thirupathi Reddy's Blog
description:
avatar: /assets/img/logo.png
language: en

#
# Icons
#
icons:
  rss: true
#  email:
  github: tguduru
#  bitbucket:
  twitter: tguduru
  linkedin: http://www.linkedin.com/in/tguduru
# youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
disqus: tguduru

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons: true

#
# Gems.
#
gems:
  - jemoji
  - jekyll-paginate

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
redcarpet:
  extensions: ["autolink", "fenced_code_blocks", "strikethrough", "superscript", "with_toc_data", "tables", "footnotes", "no_intra_emphasis"]
highlighter: pygments

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
